const jugadores = [

	{
		player: 'Acuña, Marcos',
		camiseta: 8,
		valuacion: 14,
		posicion: 'Defensor',
		club: 'Sevilla FC',
		partidos: 42,
		goles: 0,
		foto: 'imgs/macunia.png',
	},
	{
		player: 'Alvarez, Julián',
		camiseta: 9,
		valuacion: 32,
		posicion: 'Delantero',
		club: 'Manchester City',
		partidos: 11,
		goles: 2,
		foto: 'imgs/jalvarez.png',
	},
	{
		player: 'Armani, Franco',
		camiseta: 1,
		valuacion: 3,
		posicion: 'Arquero',
		club: 'Club Atlético River Plate',
		partidos: 18,
		goles: 0,
		foto: 'imgs/armani.png',
	},	
	{
		player: 'Almada, Thiago',
		camiseta: 17,
		valuacion: 15,
		posicion: 'Mediocampista',
		club: 'Atlanta United FC',
		partidos: 1,
		goles: 0,
		foto: 'imgs/almada.png',
	},	
	{
		player: 'de Paul, Rodrigo',
		camiseta: 7,
		valuacion: 35,
		posicion: 'Mediocampista',
		club: 'Atlético de Madrid',
		partidos: 43,
		goles: 2,
		foto: 'imgs/depaul.png',
	},
	{
		player: 'Di Maria, Ángel',
		camiseta: 11,
		valuacion: 10,
		posicion: 'Delantero',
		club: 'Juventus de Turín',
		partidos: 123,
		goles: 25,
		foto: 'imgs/dimaria.png',
	},
	{
		player: 'Dybala, Paulo',
		camiseta: 21,
		valuacion: 30,
		posicion: 'Delantero',
		club: 'AS Roma',
		partidos: 34,
		goles: 3,
		foto: 'imgs/dybala.png',
	},
	{
		player: 'Fernandez, Enzo',
		camiseta: 24,
		valuacion: 35,
		posicion: 'Mediocampista',
		club: 'SL Benfica',
		partidos: 2,
		goles: 0,
		foto: 'imgs/efernandez.png',
	},	
	{
		player: 'Foyth, Juan',
		camiseta: 2,
		valuacion: 25,
		posicion: 'Defensor',
		club: 'Villarreal FC',
		partidos: 15,
		goles: 0,
		foto: 'imgs/foyth.png',
	},
	{
		player: 'Gómez, Alejandro Darío',
		camiseta: 20,
		valuacion: 4,
		posicion: 'Delantero',
		club: 'Sevilla FC',
		partidos: 15,
		goles: 3,
		foto: 'imgs/pgomez.png',
	},
	{
		player: 'Correa, Angel',
		camiseta: 25,
		valuacion: 27,
		posicion: 'Delantero',
		club: 'Atlético de Madrid',
		partidos: 22,
		goles: 3,
		foto: 'imgs/acorrea.png',
	},
	{
		player: 'Mac Allister, Alexis',
		camiseta: 15,
		valuacion: 32,
		posicion: 'Mediocampista',
		club: 'Brighton & Hove Albion',
		partidos: 7,
		goles: 0,
		foto: 'imgs/macallister.png',
	},	
	{
		player: 'Martinez, Emiliano',
		camiseta: 23,
		valuacion: 25,
		posicion: 'Arquero',
		club: 'Aston Villa',
		partidos: 18,
		goles: 0,
		foto: 'imgs/emartinez.png',
	},
	{
		player: 'Martinez, Lautaro',
		camiseta: 22,
		valuacion: 75,
		posicion: 'Delantero',
		club: 'Inter de Milán',
		partidos: 40,
		goles: 21,
		foto: 'imgs/lautaro.png',
	},		
	{
		player: 'Martinez, Lisandro',
		camiseta: 16,
		valuacion: 50,
		posicion: 'Defensor',
		club: 'Manchester United',
		partidos: 9,
		goles: 0,
		foto: 'imgs/lmartinez.png',
	},
	{
		player: 'Messi, Lionel',
		camiseta: 10,
		valuacion: 50,
		posicion: 'Delantero',
		club: 'Paris Saint Germain',
		partidos: 164,
		goles: 90,
		foto: 'imgs/messi.png',
	},
	{
		player: 'Molina, Nahuel',
		camiseta: 26,
		valuacion: 18,
		posicion: 'Defensor',
		club: 'Atlético de Madrid',
		partidos: 19,
		goles: 0,
		foto: 'imgs/molina.png',
	},	
	{
		player: 'Montiel, Gonzalo',
		camiseta: 4,
		valuacion: 12,
		posicion: 'Defensor',
		club: 'Sevilla FC',
		partidos: 18,
		goles: 0,
		foto: 'imgs/montiel.png',
	},	
	{
		player: 'Otamendi, Nicolás',
		camiseta: 19,
		valuacion: 3,
		posicion: 'Defensor',
		club: 'SL Benfica',
		partidos: 92,
		goles: 4,
		foto: 'imgs/otamendi.png',
	},
	{
		player: 'Palacios, Exequiel',
		camiseta: 14,
		valuacion: 15,
		posicion: 'Mediocampista',
		club: 'Bayern 04 Leverkusen',
		partidos: 20,
		goles: 0,
		foto: 'imgs/epalacios.png',
	},
	{
		player: 'Paredes, Leandro',
		camiseta: 5,
		valuacion: 15,
		posicion: 'Mediocampista',
		club: 'Juventus de Turín',
		partidos: 45,
		goles: 4,
		foto: 'imgs/paredes.png',
	},
	{
		player: 'Pezzella, Germán',
		camiseta: 6,
		valuacion: 5,
		posicion: 'Defensor',
		club: 'Real Betis Balompié',
		partidos: 31,
		goles: 2,
		foto: 'imgs/pezzella.png',
	},
	{
		player: 'Rodriguez, Guido',
		camiseta: 18,
		valuacion: 28,
		posicion: 'Mediocampista',
		club: 'Real Betis Balompié',
		partidos: 25,
		goles: 1,
		foto: 'imgs/grodriguez.png',
	},
	{
		player: 'Romero, Cristian',
		camiseta: 13,
		valuacion: 55,
		posicion: 'Defensor',
		club: 'Tottenham Hotspur',
		partidos: 12,
		goles: 1,
		foto: 'imgs/romero.png',
	},
	{
		player: 'Rulli, Geronimo',
		camiseta: 12,
		valuacion: 10,
		posicion: 'Arquero',
		club: 'Villarreal FC',
		partidos: 4,
		goles: 0,
		foto: 'imgs/rulli.png',
	},
	{
		player: 'Tagliafico, Nicolás',
		camiseta: 3,
		valuacion: 9,
		posicion: 'Defensor',
		club: 'Olympique de Lyon',
		partidos: 42,
		goles: 0,
		foto: 'imgs/tagliafico.png',
	},

	
];
